## Tugas 2

http://localhost:8888/?token=59097b250e6e6ad272ef5e956a113e73ea267fdd64d8e416

In [19]:
!pip install mysqlclient
!pip install mysql-connector-python
!pip install pymysql
!pip install pyodbc
!pip install psycopg2
!pip install pandas

Requirement already satisfied: mysqlclient in c:\users\iis\miniconda3\lib\site-packages (2.1.1)
Requirement already satisfied: mysql-connector-python in c:\users\iis\miniconda3\lib\site-packages (8.0.32)
Requirement already satisfied: protobuf<=3.20.3,>=3.11.0 in c:\users\iis\miniconda3\lib\site-packages (from mysql-connector-python) (3.20.3)
Requirement already satisfied: pymysql in c:\users\iis\miniconda3\lib\site-packages (1.0.2)
Requirement already satisfied: pyodbc in c:\users\iis\miniconda3\lib\site-packages (4.0.35)
Requirement already satisfied: psycopg2 in c:\users\iis\miniconda3\lib\site-packages (2.9.5)
Requirement already satisfied: pandas in c:\users\iis\miniconda3\lib\site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\iis\miniconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in c:\users\iis\miniconda3\lib\site-packages (from pandas) (1.24.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\iis\miniconda3\lib\site-packages (from pandas) (2022.7.1)
Requirement already satisfied: six>=1.5 in c:\users\iis\miniconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.15.0)

In [20]:
import pyodbc 
import pandas as pd
cnxn_str = ("Driver={odbc driver 17 for sql server};"
            "Server=DESKTOP-82B6F9B\SQLEXPRESS;"
            "Database=prosain200411100174;"
            "Trusted_Connection=yes;")
cnxn = pyodbc.connect(cnxn_str)
cursor = cnxn.cursor()	
cursor.execute("SELECT * FROM dbo.petalwidthh") 
row = cursor.fetchall() 
cursor.close()
data=[]
for i in row:
    data.append([i[0],i[1],i[2]])
df_sqlServer = pd.DataFrame(data, columns=['id','petalwidth','class'])
df_sqlServer

      id petalwidth           class
0      1        0.2     Iris-setosa
1      2        0.2     Iris-setosa
2      3        0.2     Iris-setosa
3      4        0.2     Iris-setosa
4      5        0.2     Iris-setosa
..   ...        ...             ...
145  146        2.3  Iris-virginica
146  147        1.9  Iris-virginica
147  148          2  Iris-virginica
148  149        2.3  Iris-virginica
149  150        1.8  Iris-virginica

[150 rows x 3 columns]

In [21]:
import psycopg2
import pandas as pd
# Connection parameters, yours will be different
param_dic = {
    "host"      : "tiny.db.elephantsql.com",
    "database"  : "xhnmpbtl",
    "user"      : "xhnmpbtl",
    "password"  : "oWmT-kw1-VNpopQTdwgceQglfn0Nln6n"
}
def connect(params_dic):
    """ Connect to the PostgreSQL database server """
    conn = None
    try:
        # connect to the PostgreSQL server
        print('Connecting to the PostgreSQL database...')
        conn = psycopg2.connect(**params_dic)
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        sys.exit(1) 
    print("Connection successful")
    return conn

def postgresql_to_dataframe(conn, select_query, column_names):
    """
    Tranform a SELECT query into a pandas dataframe
    """
    cursor = conn.cursor()
    try:
        cursor.execute(select_query)
    except (Exception, psycopg2.DatabaseError) as error:
        print("Error: %s" % error)
        cursor.close()
        return 1
    
    # Naturally we get a list of tupples
    tupples = cursor.fetchall()
    cursor.close()
    
    # We just need to turn it into a pandas dataframe
    df = pd.DataFrame(tupples, columns=column_names)
    return df

# Connect to the database
conn = connect(param_dic)

column_names = ['id','sepalwidth']

df_postEle = postgresql_to_dataframe(conn, "select * from sepalwidthh", column_names)
df_postEle

Connecting to the PostgreSQL database...
Connection successful

      id sepalwidth
0      1        3.5
1      2          3
2      3        3.2
3      4        3.1
4      5        3.6
..   ...        ...
145  146          3
146  147        2.5
147  148          3
148  149        3.4
149  150          3

[150 rows x 2 columns]

In [22]:
import psycopg2
import pandas as pd
# Connection parameters, yours will be different
param_dic = {
    "host"      : "localhost",
    "database"  : "prosain200411100174",
    "user"      : "postgres",
    "password"  : "nurulfaizah23"
}
def connect(params_dic):
    """ Connect to the PostgreSQL database server """
    conn = None
    try:
        # connect to the PostgreSQL server
        print('Connecting to the PostgreSQL database...')
        conn = psycopg2.connect(**params_dic)
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        sys.exit(1) 
    print("Connection successful")
    return conn

def postgresql_to_dataframe(conn, select_query, column_names):
    """
    Tranform a SELECT query into a pandas dataframe
    """
    cursor = conn.cursor()
    try:
        cursor.execute(select_query)
    except (Exception, psycopg2.DatabaseError) as error:
        print("Error: %s" % error)
        cursor.close()
        return 1
    
    # Naturally we get a list of tupples
    tupples = cursor.fetchall()
    cursor.close()
    
    # We just need to turn it into a pandas dataframe
    df = pd.DataFrame(tupples, columns=column_names)
    return df

# Connect to the database
conn = connect(param_dic)

column_names = ['id','sepallength']

df_postLocal = postgresql_to_dataframe(conn, "select * from sepallengthh", column_names)
df_postLocal

Connecting to the PostgreSQL database...
Connection successful

      id sepallength
0      1         5.1
1      2         4.9
2      3         4.7
3      4         4.6
4      5           5
..   ...         ...
145  146         6.7
146  147         6.3
147  148         6.5
148  149         6.2
149  150         5.9

[150 rows x 2 columns]

In [23]:
!pip install mysqlclient
!pip install mysql-connector-python
!pip install pymysql

Requirement already satisfied: mysqlclient in c:\users\iis\miniconda3\lib\site-packages (2.1.1)
Requirement already satisfied: mysql-connector-python in c:\users\iis\miniconda3\lib\site-packages (8.0.32)
Requirement already satisfied: protobuf<=3.20.3,>=3.11.0 in c:\users\iis\miniconda3\lib\site-packages (from mysql-connector-python) (3.20.3)
Requirement already satisfied: pymysql in c:\users\iis\miniconda3\lib\site-packages (1.0.2)

In [24]:
import mysql.connector
import pandas as pd

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="",
  database="prosain200411100174"
)

mycursor = mydb.cursor()

mycursor.execute("SELECT * FROM petallengthh")

myresult = mycursor.fetchall()
mycursor.close()
df_mysql = pd.DataFrame(myresult, columns=['id','petallength'])
# df_mysql.drop(df_mysql.columns[[0]],axis=1,inplace=True)
df_mysql

      id petallength
0      1         1.4
1      2         1.4
2      3         1.3
3      4         1.5
4      5         1.4
..   ...         ...
145  146         5.2
146  147           5
147  148         5.2
148  149         5.4
149  150         5.1

[150 rows x 2 columns]

In [25]:
# merge df
result = pd.concat([df_postLocal, df_postEle,df_mysql, df_sqlServer], axis=1)
#result = pd.merge(df_postLocal,df_sqlServer, how="inner", on=["id", "id"])
result

,id,sepallength,id,sepalwidth,id,petallength,id,petalwidth,class
0,1,5.1,1,3.5,1,1.4,1,0.2,Iris-setosa
1,2,4.9,2,3,2,1.4,2,0.2,Iris-setosa
2,3,4.7,3,3.2,3,1.3,3,0.2,Iris-setosa
3,4,4.6,4,3.1,4,1.5,4,0.2,Iris-setosa
4,5,5,5,3.6,5,1.4,5,0.2,Iris-setosa
...,...,...,...,...,...,...,...,...,...
145,146,6.7,146,3,146,5.2,146,2.3,Iris-virginica
146,147,6.3,147,2.5,147,5,147,1.9,Iris-virginica
147,148,6.5,148,3,148,5.2,148,2,Iris-virginica
148,149,6.2,149,3.4,149,5.4,149,2.3,Iris-virginica
149,150,5.9,150,3,150,5.1,150,1.8,Iris-virginica

In [26]:
result.drop(result.columns[[0,2,4,6]],axis=1,inplace=True)
result

    sepallength sepalwidth petallength petalwidth           class
0           5.1        3.5         1.4        0.2     Iris-setosa
1           4.9          3         1.4        0.2     Iris-setosa
2           4.7        3.2         1.3        0.2     Iris-setosa
3           4.6        3.1         1.5        0.2     Iris-setosa
4             5        3.6         1.4        0.2     Iris-setosa
..          ...        ...         ...        ...             ...
145         6.7          3         5.2        2.3  Iris-virginica
146         6.3        2.5           5        1.9  Iris-virginica
147         6.5          3         5.2          2  Iris-virginica
148         6.2        3.4         5.4        2.3  Iris-virginica
149         5.9          3         5.1        1.8  Iris-virginica

[150 rows x 5 columns]

In [27]:
X = result.values[:, :4]
Y = result.values[:, 4]
print(X)

[['5.1' '3.5' '1.4' '0.2']
 ['4.9' '3' '1.4' '0.2']
 ['4.7' '3.2' '1.3' '0.2']
 ['4.6' '3.1' '1.5' '0.2']
 ['5' '3.6' '1.4' '0.2']
 ['5.4' '3.9' '1.7' '0.4']
 ['4.6' '3.4' '1.4' '0.3']
 ['5' '3.4' '1.5' '0.2']
 ['4.4' '2.9' '1.4' '0.2']
 ['4.9' '3.1' '1.5' '0.1']
 ['5.4' '3.7' '1.5' '0.2']
 ['4.8' '3.4' '1.6' '0.2']
 ['4.8' '3' '1.4' '0.1']
 ['4.3' '3' '1.1' '0.1']
 ['5.8' '4' '1.2' '0.2']
 ['5.7' '4.4' '1.5' '0.4']
 ['5.4' '3.9' '1.3' '0.4']
 ['5.1' '3.5' '1.4' '0.3']
 ['5.7' '3.8' '1.7' '0.3']
 ['5.1' '3.8' '1.5' '0.3']
 ['5.4' '3.4' '1.7' '0.2']
 ['5.1' '3.7' '1.5' '0.4']
 ['4.6' '3.6' '1' '0.2']
 ['5.1' '3.3' '1.7' '0.5']
 ['4.8' '3.4' '1.9' '0.2']
 ['5' '3' '1.6' '0.2']
 ['5' '3.4' '1.6' '0.4']
 ['5.2' '3.5' '1.5' '0.2']
 ['5.2' '3.4' '1.4' '0.2']
 ['4.7' '3.2' '1.6' '0.2']
 ['4.8' '3.1' '1.6' '0.2']
 ['5.4' '3.4' '1.5' '0.4']
 ['5.2' '4.1' '1.5' '0.1']
 ['5.5' '4.2' '1.4' '0.2']
 ['4.9' '3.1' '1.5' '0.1']
 ['5' '3.2' '1.2' '0.2']
 ['5.5' '3.5' '1.3' '0.2']
 ['4.9' '3.1' '1.5' '0.1']
 ['4.4' '3' '1.3' '0.2']
 ['5.1' '3.4' '1.5' '0.2']
 ['5' '3.5' '1.3' '0.3']
 ['4.5' '2.3' '1.3' '0.3']
 ['4.4' '3.2' '1.3' '0.2']
 ['5' '3.5' '1.6' '0.6']
 ['5.1' '3.8' '1.9' '0.4']
 ['4.8' '3' '1.4' '0.3']
 ['5.1' '3.8' '1.6' '0.2']
 ['4.6' '3.2' '1.4' '0.2']
 ['5.3' '3.7' '1.5' '0.2']
 ['5' '3.3' '1.4' '0.2']
 ['7' '3.2' '4.7' '1.4']
 ['6.4' '3.2' '4.5' '1.5']
 ['6.9' '3.1' '4.9' '1.5']
 ['5.5' '2.3' '4' '1.3']
 ['6.5' '2.8' '4.6' '1.5']
 ['5.7' '2.8' '4.5' '1.3']
 ['6.3' '3.3' '4.7' '1.6']
 ['4.9' '2.4' '3.3' '1']
 ['6.6' '2.9' '4.6' '1.3']
 ['5.2' '2.7' '3.9' '1.4']
 ['5' '2' '3.5' '1']
 ['5.9' '3' '4.2' '1.5']
 ['6' '2.2' '4' '1']
 ['6.1' '2.9' '4.7' '1.4']
 ['5.6' '2.9' '3.6' '1.3']
 ['6.7' '3.1' '4.4' '1.4']
 ['5.6' '3' '4.5' '1.5']
 ['5.8' '2.7' '4.1' '1']
 ['6.2' '2.2' '4.5' '1.5']
 ['5.6' '2.5' '3.9' '1.1']
 ['5.9' '3.2' '4.8' '1.8']
 ['6.1' '2.8' '4' '1.3']
 ['6.3' '2.5' '4.9' '1.5']
 ['6.1' '2.8' '4.7' '1.2']
 ['6.4' '2.9' '4.3' '1.3']
 ['6.6' '3' '4.4' '1.4']
 ['6.8' '2.8' '4.8' '1.4']
 ['6.7' '3' '5' '1.7']
 ['6' '2.9' '4.5' '1.5']
 ['5.7' '2.6' '3.5' '1']
 ['5.5' '2.4' '3.8' '1.1']
 ['5.5' '2.4' '3.7' '1']
 ['5.8' '2.7' '3.9' '1.2']
 ['6' '2.7' '5.1' '1.6']
 ['5.4' '3' '4.5' '1.5']
 ['6' '3.4' '4.5' '1.6']
 ['6.7' '3.1' '4.7' '1.5']
 ['6.3' '2.3' '4.4' '1.3']
 ['5.6' '3' '4.1' '1.3']
 ['5.5' '2.5' '4' '1.3']
 ['5.5' '2.6' '4.4' '1.2']
 ['6.1' '3' '4.6' '1.4']
 ['5.8' '2.6' '4' '1.2']
 ['5' '2.3' '3.3' '1']
 ['5.6' '2.7' '4.2' '1.3']
 ['5.7' '3' '4.2' '1.2']
 ['5.7' '2.9' '4.2' '1.3']
 ['6.2' '2.9' '4.3' '1.3']
 ['5.1' '2.5' '3' '1.1']
 ['5.7' '2.8' '4.1' '1.3']
 ['6.3' '3.3' '6' '2.5']
 ['5.8' '2.7' '5.1' '1.9']
 ['7.1' '3' '5.9' '2.1']
 ['6.3' '2.9' '5.6' '1.8']
 ['6.5' '3' '5.8' '2.2']
 ['7.6' '3' '6.6' '2.1']
 ['4.9' '2.5' '4.5' '1.7']
 ['7.3' '2.9' '6.3' '1.8']
 ['6.7' '2.5' '5.8' '1.8']
 ['7.2' '3.6' '6.1' '2.5']
 ['6.5' '3.2' '5.1' '2']
 ['6.4' '2.7' '5.3' '1.9']
 ['6.8' '3' '5.5' '2.1']
 ['5.7' '2.5' '5' '2']
 ['5.8' '2.8' '5.1' '2.4']
 ['6.4' '3.2' '5.3' '2.3']
 ['6.5' '3' '5.5' '1.8']
 ['7.7' '3.8' '6.7' '2.2']
 ['7.7' '2.6' '6.9' '2.3']
 ['6' '2.2' '5' '1.5']
 ['6.9' '3.2' '5.7' '2.3']
 ['5.6' '2.8' '4.9' '2']
 ['7.7' '2.8' '6.7' '2']
 ['6.3' '2.7' '4.9' '1.8']
 ['6.7' '3.3' '5.7' '2.1']
 ['7.2' '3.2' '6' '1.8']
 ['6.2' '2.8' '4.8' '1.8']
 ['6.1' '3' '4.9' '1.8']
 ['6.4' '2.8' '5.6' '2.1']
 ['7.2' '3' '5.8' '1.6']
 ['7.4' '2.8' '6.1' '1.9']
 ['7.9' '3.8' '6.4' '2']
 ['6.4' '2.8' '5.6' '2.2']
 ['6.3' '2.8' '5.1' '1.5']
 ['6.1' '2.6' '5.6' '1.4']
 ['7.7' '3' '6.1' '2.3']
 ['6.3' '3.4' '5.6' '2.4']
 ['6.4' '3.1' '5.5' '1.8']
 ['6' '3' '4.8' '1.8']
 ['6.9' '3.1' '5.4' '2.1']
 ['6.7' '3.1' '5.6' '2.4']
 ['6.9' '3.1' '5.1' '2.3']
 ['5.8' '2.7' '5.1' '1.9']
 ['6.8' '3.2' '5.9' '2.3']
 ['6.7' '3.3' '5.7' '2.5']
 ['6.7' '3' '5.2' '2.3']
 ['6.3' '2.5' '5' '1.9']
 ['6.5' '3' '5.2' '2']
 ['6.2' '3.4' '5.4' '2.3']
 ['5.9' '3' '5.1' '1.8']]

In [28]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\iis\miniconda3\lib\site-packages (1.2.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\iis\miniconda3\lib\site-packages (from scikit-learn) (3.1.0)
Requirement already satisfied: numpy>=1.17.3 in c:\users\iis\miniconda3\lib\site-packages (from scikit-learn) (1.24.2)
Requirement already satisfied: joblib>=1.1.1 in c:\users\iis\miniconda3\lib\site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: scipy>=1.3.2 in c:\users\iis\miniconda3\lib\site-packages (from scikit-learn) (1.10.1)

### Model PCA

In [29]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)

In [30]:
pca.fit(X)

PCA(n_components=2)

In [31]:
pca.components_

array([[ 0.36158968, -0.08226889,  0.85657211,  0.35884393],
       [ 0.65653988,  0.72971237, -0.1757674 , -0.07470647]])

In [32]:
Z = pca.transform(X)

In [33]:
Z.shape

(150, 2)

PEMBAGIAN DATA TESTING DAN TRAINING

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( 
    X, Y, test_size = 0.2, random_state = 100)

In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
# from sklearn.decomposition import PCA

# pca = PCA()
# X_train = pca.fit_transform(X_train)
# X_test = pca.transform(X_test)

In [ ]:
# pca.get_covariance()

In [ ]:
# explained_variance = pca.explained_variance_ratio_
# explained_variance

In [ ]:
# from sklearn.decomposition import PCA

# pca = PCA(n_components=2)
# X_train = pca.fit_transform(X_train)
# X_test = pca.transform(X_test)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
print (" DecisionTree Accuracy : ",
    accuracy_score(y_test,y_pred)*100)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
print (" KNN Accuracy : ",
    accuracy_score(y_test,y_pred)*100)